- bolt_386.go
- bolt_arm.go
> Raise maxMapSize from 256MB to 2GB on 386, arm.

- README.md
There was one curly brace too much
> Fix syntax error in README stats example

- bolt_unix.go
This commit fixes an issue with ext3/ext4 filesystems where metadata file size is not synced when resizing a file. It also resizes the entire resize instead of updating the size during individual page writes.
Fixes #284.
Thanks to @tv42 for the fix.
> Add truncate() and sync() on resize.

- README.md
Due to the fact that you want to iterate over all keys that are before or equal to `max` starting from `min` the bytes.Compare() check should look like the commit suggests.
> fix 'range scans' example

- db.go
Presume it was a mistake, doesn't do any harm but is redundant code
> Removed redundant duplicate line of code

- db.go
- db_test.go
This pull request fixes an issue where the database would grow whenever it was opened. This was caused by a recent change that performed a truncation when the database grew. Now there are fixed growth sizes for the database (1MB, 2MB, 4MB, 8MB, etc) up to 1GB and then the database will grow by 1GB when it resizes.
See also: 6bb25854a183f3d3bfa50096f910d3a3984e9834
Fixes: #291
/cc @kemist
> Fix mmap resize calculation.

- bucket.go
- cursor.go
- db.go
- freelist.go
- node.go
This pull request expands calls to `_assert()` that use variadic arguments. These calls require conversion to `interface{}` so there was a large number of calls to Go's internal `convT2E()` function. In some profiling this was taking over 20% of total runtime. I don't remember seeing this before Go 1.4 so perhaps something has changed. Or maybe I just didn't see it.
Note that this does not change any functionality. The changed lines of code are functionally equivalent.
---
/cc @mkobetic
> Expand assertion statements

- bucket.go
- bucket_test.go
- db.go
- db_test.go
This commit fixes a bug where only calling NextSequence() on a Bucket does not cause the Bucket to be peristed. The simple fix is to simply materialize the root node so that the bucket is flushed out during commit.
Thanks to Matthew Dawson (@MJDSys) for reporting.
Fixes #296
> Persist sequence-only changes

- README.md
Simple typo, a missing parenthesis in one of the examples of the README.
> Fixed missing parenthesis on the readme

- page.go
This commit changes the maxAllocSize from 256GB to 2GB to handle large values. It was previously 0xFFFFFFF and I tried adding one more "F" but it caused an "array too large" error. I played around with the value some more and found that 0x7FFFFFFF (2GB) is the highest allowed value.
This does not affect how the data is stored. It is simply used for type converting pointers to array pointers in order to utilize zero copy from the mmap.
Fixes #299
/cc @stryke @denistoikka @kemist
> Increase max array pointer size to 2GB.

- bolt_386.go
- bolt_amd64.go
- page.go
This pull request fixes a breaking change introduce to the 32-bit architecture in https://github.com/boltdb/bolt/pull/315. The fix is to simply revert the value of `maxAllocSize` for the 386 arch only.
---
Fixes: https://github.com/boltdb/bolt/issues/316
/cc @poffe
> Update max alloc size on 386 arch

- bolt_arm.go
Added max alloc size to the arm arch, because I was running bolt on a Pi2 and it wouldn't compile.
> Added max alloc size to arm.

- cmd/bolt/info.go
A new line at the end of page size info printing would be good
> new line after page size info print

- README.md
- batch.go
- batch_benchmark_test.go
- batch_example_test.go
- batch_test.go
- db.go
- db_test.go
Batcher makes it easy to make lots of small transactions with
significantly better performance. Batcher.Update combines multiple
Update calls into a single disk transaction, managing errors smartly.
I'm aware of https://github.com/boltdb/coalescer. I wrote the original version of this before you pushed coalescer, it just took a while for me to circle back to cleaning it up. This code doesn't leave a goroutine around, and is a few percent faster ;) But the real difference to coalescer is this: with this code, callers don't need to write a for loop around ErrRollback. I pull failing updaters out of the transaction, and retry the others automatically.
I'd really like to see this as part of bolt, and I feel like having a good batcher mechanism would help significantly with performance …
> Add transaction batching

- README.md
- tx.go
This pull request moves the functionality in `Tx.Copy()` to `Tx.WriteTo()`. This allows `Tx` to be used as an `io.WriterTo` which makes it easier to mock.
The `Tx.Copy()` function still exists but it's simply a wrapper around `Tx.WriteTo()`.
> Implement io.WriterTo interface on Tx.

- README.md
- tx.go
Added Freehold to the projects list in README.
Added a few lines of documentation to clarify that read-only
transactions need to be rolled back and not committed, as per the
discussion in issue #344.
> Added Freehold to the projects list in README + Transaction Documentation change

- cmd/bolt/main.go
Fix https://github.com/boltdb/bolt/issues/353
> cmd/bolt: remove duplicate blockProfile flag

- bolt_unix.go
- db.go
This commit adds the `DB.NoTruncate` flag to optionally revert `mmap()` calls to how they were implemented before the ext3/ext4 fix. When `NoTruncate` is true, remapping the data file will not force the file system to resize it immediately. This works for non-ext3/4 file systems.
The default value of `NoTruncate` is `false` so it is still safe for ext3/ext4 file systems by default.
See also: https://github.com/boltdb/bolt/issues/284
/cc @tv42 @mkobetic @bouk
> Add DB.NoTruncate flag.

- db.go
This pull request adds `DB.Sync()` for users who set `DB.NoSync` to `true`. This ensures `NoSync` commits are safe after syncing but it still provides no guarantees to `NoSync` before syncing.
Note: Please use `NoSync` carefully. Partially written commits can corrupt your database when using `NoSync`.
Fixes https://github.com/boltdb/bolt/issues/364
> Add DB.Sync()

- bolt_amd64.go
- node.go
- page.go
- tx.go
when accessing the node data we used to use cast to
*[maxAllocSize]byte, which breaks if we try to go across maxAllocSize boundary.
This leads to occasional panics.
Sample stacktrace:
```
panic: runtime error: slice bounds out of range
goroutine 1 [running]:
github.com/boltdb/bolt.(*node).write(0xc208010f50, 0xc27452a000)
$GOPATH/src/github.com/boltdb/bolt/node.go:228 +0x5a5
github.com/boltdb/bolt.(*node).spill(0xc208010f50, 0x0, 0x0)
$GOPATH/src/github.com/boltdb/bolt/node.go:364 +0x506
github.com/boltdb/bolt.(*node).spill(0xc208010700, 0x0, 0x0)
$GOPATH/src/github.com/boltdb/bolt/node.go:336 +0x12d
github.com/boltdb/bolt.(*node).spill(0xc208010620, 0x0, 0x0)
$GOPATH/src/github.com/boltdb/bolt/node.go:336 +0x12d
github.com/boltdb/bolt.(*Bucket).spill(0xc22b6ae880, 0x0, 0x0) …
```
> fix `slice bounds out of range`/maxAllocSize bugs

- db.go
This pull request adjusts the minimum mmap size from 1MB to 32KB. The previous limit was arbitrary and causes wasted space for very small databases.
Thanks to @mcuadros for submitting the original pull request: https://github.com/boltdb/bolt/pull/351
> Change min mmap size from 1MB to 32KB.

- bolt_unix.go
- bolt_windows.go
- db.go
- db_test.go
- errors.go
allows a database to be opened by multiple processes at the same time in read-only mode.
all attempts to mutate the database result in ErrDatabaseReadOnly.
> open read-only databases in read-only mode

- README.md
[Consul](https://github.com/hashicorp/consul) has recently switched to using BoltDB as its backend store. It is used to store Raft logs to persist cluster state, and so far we love it! It has enabled us to shed the pain of compiling for multiple platforms with CGO. Keep up the great work, and thank you!
> Add Consul to README

- db.go
- db_test.go
This pull request fixes the `DB.Close()` function so that it waits for any open transactions to finish before closing.
Previously a close would shutdown the `DB` immediately and cause a panic in any open transactions, however, no data corruption would occur.
Fixes: https://github.com/boltdb/bolt/issues/341
> Wait for pending transactions on close

- README.md
- db.go
This pull request adds documentation to clarify that read-only and read-write transactions should not be mixed in the same goroutine as it can cause deadlocks during remapping.
See: https://github.com/boltdb/bolt/issues/378
/cc @mschoch
> Add docs for dependent transactions.

- bolt_unix.go
This pull request advises the memory-mapped data file to use `MADV_RANDOM` to avoid readahead. This can provide a performance boost to Bolt databases that are larger than memory by avoiding unnecessary disk I/O.
> Add madvise() after mmap().

- bucket_test.go
Adds test coverage for these lines: https://github.com/boltdb/bolt/blob/master/bucket.go#L283-L285
```
[zsh|matt@nerr-2]:~/git/go/src/github.com/boltdb/bolt 0 *(master) ± go test -v -run=TestBucket_Put_ValueTooLarge
seed: 46260
quick settings: count=5, items=1000, ksize=1024, vsize=1024
=== RUN TestBucket_Put_ValueTooLarge
--- PASS: TestBucket_Put_ValueTooLarge (0.40s)
PASS
ok      github.com/boltdb/bolt  0.408s
```
> bucket_test: add test for ErrValueTooLarge on insert

- bucket_test.go
This pull request ignores the `TestBucket_Put_ValueTooLarge` test on Drone CI because the containers do not have enough memory. This test will still be run by anyone else who runs the test suite so that will still provide coverage.
> Fix Drone CI

- batch.go
This commit adds documentation for batch size and delay to the `DB.Batch()` call. Previously there was no reference to these properties from the `Batch()` call so it was nearly impossible for anyone to know to adjust these settings.
Thanks to Kelly Sommers (@kellabyte) for bringing the doc issue to my attention. :tada: :tada: :tada:
> Add batch size and delay docs

- cmd/bolt/main.go
`go vet` discovered two calls of Fprintln with trailing newline and one
Errorf call without proper format string.
> Fix invalid fmt.Fprintln/Errorf calls

- bolt_unix_solaris.go
- db_test.go
* Many thanks to @akolb1 for the FcntlFlock based flock implementation.
* Requires recent golang.org/x/sys/unix for fixed mmap,munmap,madvise.
* Fixes #274 and fixes #305.
* Addresses part of #345.
* Solaris fcntl locks don't support intra-process locking
Three unit tests were failing, now are skipped on solaris only:
```
seed: 68195
quick settings: count=5, items=1000, ksize=1024, vsize=1024
00010000000000000000000000000000
db_test.go:57: 
--- FAIL: TestOpen_Timeout (0.00s)
db_test.go:86: 
--- FAIL: TestOpen_Wait (0.00s)
db_test.go:257: 
--- FAIL: TestOpen_ReadOnly (0.00s)
FAIL
exit status 1
FAIL    github.com/boltdb/bolt  354.617s
```
* FcntlFlock treats separate locks on separate file descriptors differently then Flock.
* Flock semantics are preferrable for multithreaded servers.
* No …
> solaris: fix issues with mmap, munmap, madvise and flock

- tx.go
This pull request removes references to the last write transaction and and its dirty pages after the transaction has been closed. This bug did not affect the safety of the data, however, it would cause dirty pages to linger in-memory until the next write transaction began.
> Release read-write Tx after close

- bolt_arm64.go
Support arm64 architecture
Signed-off-by: jefby <jef199006@gmail.com>
> add bolt_arm64.go for arm64

- bolt_arm64.go
This pull request removes the arm64 change because it caused issues with Go 1.4.
Fixes #416.
> Revert arm64 change

- README.md
So, [stow](https://github.com/djherbis/stow) is just a little utility to simplify de/encoding values and [buckets](https://github.com/joyrexus/buckets) is a tiny wrapper/extension, but some might find 'em handy for the particular use cases they're targeting.
I considered adding [simplebolt](https://github.com/xyproto/simplebolt) as well, but that might qualify as more of a personal experiment than something designed for other users.  Not sure.  (I guess there are tests and a license.)
Feel free to close/reject this pull request if you'd prefer a separate sub-heading in the README for utilities/extensions/experiments, restricting the current list to notable public/opensource projects?  Or perhaps a project wiki page, organized by broad categories?
> Add two little projects to README project list

- bolt_arm64.go
Added build tag for arm64, so we won't get any errors on other
platforms with go 1.4.x.
Signed-off-by: Qiang Huang <h.huangqiang@huawei.com>
> Add support for arm64

- bucket_test.go
When removing all the keys from the bucket, use Cursor.Delete directly, which
avoids a seek through the bucket to find the element to delete.  This knocks
1/5 of the time off my laptop when running this test while not reducing the
amount of overflow pages cleared out of the free list.
> In TestBucket_Delete_FreelistOverflow, use Cursor.Delete to remove records.

- README.md
I have been bitten by this when running a simple application on a
Raspberry Pi 2. It had 3 stores: two 512M stores and one 128M. The
application refused to start the moment the first index grew from 512M
to 1G.
Bolt is really nice but it is easy to overlook this limitation,
especially with the note about supporting stores much larger than
*physical* memory.
> README: mention the memory map consumes a lot of address space

- bucket.go
- tx.go
Issue #313 
Might be a bit heavy handed, but it does the job.
> bucket: document buckets are valid only during the transaction

- bucket.go
Issue #324
I have been bitten by this too. Let's try to move forward on the documentation (or implementation).
> bucket: document Put() value must remain valid for the transaction

- bucket.go
This pull request changes the maximum value size from 4GB to 2GB so that tests can run on 32-bit machines. There's really no reason to write a 2GB+ value to Bolt. Bolt is not terribly efficient for large values.
> Lower MaxValue to 2GB

- bolt_windows.go
- db_test.go
I added file locking for Windows. Some links to reference constant sources are included.
Tested manually using an example program that simply opens a DB and waits for signal, against Windows XP (sadly, my target platform). According to MSDN this should work on future platforms also, see referenced documentation.
The timeout support was derived from flock_unix.go.
> windows: implement file locking

- bolt_linux.go
- bolt_openbsd.go
- bolt_windows.go
- tx.go
For in memory workload, it does not make sense to use
o_direct to copy the file. Adding a option to clear out
o_direct and for other future cases.
> add WriteToFlag to Tx

- cursor.go
- cursor_test.go
This commit fixes an issue where keys are skipped by cursors after deletions occur in a bucket. This occurred because the cursor seeks to the leaf page but does not check if it is empty.
Fixes #429, #450
---
@lukechampine Thanks for digging into this and figuring it out. The fix you made makes sense. The cursor needs to move forward to the next item if an empty page is found. I made a small tweak to the fix inside `next()` so that it doesn't recursively call itself. I also added a test case to check for it. I added you as the commit author, though, for attribution.
Can you take a look and verify that this fix works for you in your project?
> Skip empty pages during cursor seek

- bolt_unix.go
- bolt_unix_solaris.go
- db.go
/cc @xiang90 
This adds MmapFlags to set syscall.MAP_POPULATE in Linux 2.6.23+.
If true, it would do the sequential read-ahead, as discussed in [1].
Xiang helped me on this PR. I benchmarked the READ performance and with `MAP_POPULATE` flag,
its read performance increased. I did:
1. Generated random data of 2GB.
2. Clean up page cache `echo "echo 1 > /proc/sys/vm/drop_caches" | sudo sh`
3. Read **with** and **without** `MAP_POPULATE` and compare two results [2].
<br>
Results
- SSD, Ubuntu, Intel(R) Core(TM) i7-4910MQ CPU @ 2.90GHz, go version go1.5.1 linux/amd64, Linux kernel version: 3.16.0-52-generic
For 2GB, read takes 8 seconds without `MAP_POPULATE`, 4 seconds WITH `MAP_POPULATE`.
<br>
- HDD, 1 vCPU, 3.75 GB Memory, Google Cloud, Intel(R) Xeon(R) CPU @ 2.30GHz, go version go1.5.1 …
> Add MmapFlags option for MAP_POPULATE (unix)

- README.md
- tx.go
I had to dig into the code a bit to understand how sub-buckets work when iterating with a Cursor, so I added that information to the README.
> Document iterating over buckets

- README.md
All other forms of `FunctionName()` use backticks for formatting, so adding it around NextSequence() too.
> Put backticks around function name in description

- cmd/bolt/main.go
- cmd/bolt/main_test.go
Fixing a division by zero and adding a new test case.
> Fix `bolt stats` output

- db.go
- db_test.go
Errors from calling `bolt.Open` will be as documented in `errors.go`:
> **ErrInvalid** is returned when a data file is not a Bolt-formatted database.
> **ErrVersionMismatch** is returned when the data file was created with a different version of Bolt.
> **ErrChecksum** is returned when either meta page checksum does not match.
Fixes #468.
> Make bolt.Open return the documented errors

- db.go
- db_test.go
`InitialMmapSize` is the initial mmap size of the database in bytes.
Read transaction won't block write transaction if InitialMmapSize
is large enough to handle mmap size.
Copied from https://github.com/boltdb/bolt/pull/432.
/cc @xiang90 @benbjohnson 
I took this over from @xiang90  and confirmed that current implementation
easily causes deadlock when we pass 0 for `db.mmap`. You can simply reproduce
as follows:
```go
package main
import (
"fmt"
"math/rand"
"os"
"time"
"github.com/boltdb/bolt"
)
var (
dbPath     = "test.db"
bucketName = "test"
numKeys = 100
keyLen = 100
valLen = 750
keys = make([][]byte, numKeys)
vals = make([][]byte, numKeys)
)
func init() {
fmt.Println("Starting generating random data...")
for i := range keys {
keys[i] = randBytes(keyLen)
vals[i] = randBytes(valLen)
} …
```
> Introduce InitialMmapSize to prevent deadlock

- db.go
The size changed back in https://github.com/boltdb/bolt/pull/375, while the doc has not been updated.
> Update min mmap size in godoc

- README.md
- Generated and tweaked a TOC using [doctoc](https://github.com/thlorenz/doctoc)
- Removed auto-generated headers and fixed broken ampersand conversion - ` & ` should be `--`
Happy to shuffle the position of the TOC. Writing some stuff against BoltDB right now and found the README invaluable but just wanted a quicker way to skim it besides Cmd+F!
> [docs] Add table of contents

- bolt_unix.go
- bolt_unix_solaris.go
- db.go
- db_test.go
- tx.go
Only grow the database size when the high watermark increases.
We also grows the database size a little bit aggressively to
save a few ftruncates and fsyncs.
I have tested this on various environments. The performance impact
is ignorable with 16MB over allocation. Without over allocation,
the performance might decrease 100% when each Tx.Commit needs a new
page on a very slow disk (seek time dominates the total write).
We will not overallocate 16MB when the database is small since it also
limits by the datasz.
> do not grow dbsize agressively

- README.md
> Add documentation to Readme for mobile support (iOS/Android)

- README.md
Add check if bucket exists before use in examples of db.View in readme.md code examples. This check prevents a runtime panic when `db.View()` uses the bucket when nil e.g. `b.Cursor()`.
Since the readme is the most used guide by beginners, this would help avoiding this common learner panic::
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x8 pc=0x4012bf]
goroutine 1 [running]:
main.main.func1(0xc82007c000, 0x0, 0x0)
/home/chief/go/src/bitbucket.org/etelej/appx/main.go:21 +0x8f
github.com/boltdb/bolt.(*DB).View(0xc820060820, 0x57d308, 0x0, 0x0)
/home/chief/go/src/github.com/boltdb/bolt/db.go:583 +0xb9
main.main()
/home/chief/go/src/bitbucket.org/etelej/appx/main.go:26 +0x177
exit status 2
```
> Add bucket check to db.View in readme.md

- bolt_arm64.go
This was preventing ARM64 targets from building.
> Remove erroneous build constraint from arm64

- appveyor.yml
Add an initial appveryor.yml to test on AppVeyor's Windows CI.
See here for a sample run: https://ci.appveyor.com/project/MJDSys/bolt/build/2
They provide free accounts for open source software.  I signed up with no issue to test this.
> Add appveyor.yml.

- bolt_ppc.go
Adding this file allowed me to compile and run bolt in Linux on my old 32-bit PPC Mac Mini.
```
$ cat /proc/cpuinfo 
processor	: 0
cpu			: 7447A, altivec supported
clock		: 1249.999995MHz
revision		: 1.2 (pvr 8003 0102)
bogomips	: 83.24
total bogomips	: 83.24
timebase		: 41620997
platform		: PowerMac
model		: PowerMac10,1
machine		: PowerMac10,1
motherboard	: PowerMac10,1 MacRISC3 Power Macintosh 
detected as	: 287 (Mac mini)
pmac flags	: 00000010
L2 cache		: 512K unified
pmac-generation	: NewWorld
Memory		: 1024 MB
```
> Add bolt_ppc.go to compile on 32-bit PPC platforms.

- tx.go
- tx_test.go
This commit changes `Tx.WriteTo()` to use the transaction's in-memory meta page instead of copying from the disk. This is needed because the transaction uses the size from its meta page but writes the current meta page on disk which may have allocated additional pages since the transaction started.
Fixes #513
/cc @xiang90
> Use tx.meta during Tx.WriteTo()

- bolt_unix.go
- bolt_unix_solaris.go
- bolt_windows.go
- db.go
On Windows, `LockFileEx` doesn't allow a process to have an exclusive lock on a file and then open a separate handle on the same file. This pull request also fixes an issue with `Truncate()` during file growth.
> Move to separate lock file on windows

- node.go
This commit fixes a rare issue where a page can become accessible when it has already been freed. This occurs when the first two child pages of a parent both have deletions and the first page
has 1 remaining children and the second page has 2 remaining children. During rebalancing the first page pulls an element from the second page and then the second page pulls the same element back from the first. The child page was not being freed properly.
I resolved this issue by removing this part of the rebalancing.
I made this choice for two reasons:
1. Moving a single item between pages has negligible benefit. The page will eventually be cleaned up when it reaches zero elements.
2. This is an infrequently executed branch of code which increases the likelihood of bugs occurring and it makes it …
> Fix rebalance bug

- README.md
RFC3339 is sortable, but RFC3339Nano is not, because it does not use a fixed number of digits after the decimal.
Fixes #536
> Add note about Go RFC3339Nano sortability to README

- README.md
Remove the Drone.IO badge while setting up new test infrastructure. Currently the simulation tests in the test suite fail because it runs for too long.
> Remove badge

- bucket_test.go
- page.go
This commit sets the capacity on slices returned from `Bucket.Get()` to match the slice length. Previously the capacity would be the size of the mmap max size.
This does not cause any backwards compatibility issues, however, it does allow users to `append()` to the returned slice since that will cause Go to realloc a new slice on the heap.
Fixes #544
/cc @sasha-s
> Set slice capacity

- db.go
The Windows version of funlock needs the db.path to delete the
corresponding .lock file.
Fix for #549.
> Delay clearing db.path until just before db.close returns.

- db.go
- tx.go
I used #409 as a base for this patch. I decided to treat only `count == 1` as a small page. Also pool is used only for databases with `pageSize == os.Getpagesize`. I think that it's possible to create dynamic pool for each `pageSize` in system, but it's not worth it.
Benchmark results:
```
benchmark                          old ns/op     new ns/op     delta
BenchmarkDBBatchAutomatic-4        2552625       2485200       -2.64%
BenchmarkDBBatchSingle-4           59632698      50757603      -14.88%
BenchmarkDBBatchManual10x100-4     2564789       2452735       -4.37%
benchmark                          old allocs     new allocs     delta
BenchmarkDBBatchAutomatic-4        10199          10202          +0.03%
BenchmarkDBBatchSingle-4           56642          56653          +0.02% …
```
> Use sync.Pool for small pages in db.allocate

- db.go
Bolt stores the two latest transactions' metadata, but previously did
not recover from validation failures in the latest by using the second
latest. Fix this by correctly handling validation failures in db.go, as
well as returning the metadata with highest txid which is also valid in
DB.meta().
Fixes: #548
Signed-off-by: Aleksa Sarai <asarai@suse.de>
/cc @benbjohnson
> db: fix recovery from unsynced metadata

- freelist.go
- node.go
- page.go
This commit fixes a bug where page end-of-header pointers were being converted to byte slices even when the pointer did not point to allocated memory. This occurs with pages that have a `page.count` of zero.
Note: This was not an issue in Go 1.6 but the new Go 1.7 SSA backend handles `nil` checks differently.
See https://github.com/golang/go/issues/16772
/cc @zeebo
> Fix Go 1.7 pointer reference bug

- freelist.go
Here is a profile taken etcd.
Before:
```
10924      10924 (flat, cum)  4.99% of Total
.          .    230:
.          .    231:// reindex rebuilds the free cache based on available and pending free lists.
.          .    232:func (f *freelist) reindex() {
.          .    233:	f.cache = make(map[pgid]bool)
.          .    234:	for _, id := range f.ids {
10924      10924    235:		f.cache[id] = true
.          .    236:	}
.          .    237:	for _, pendingIDs := range f.pending {
.          .    238:		for _, pendingID := range pendingIDs {
.          .    239:			f.cache[pendingID] = true
.          .    240:		}
```
After:
```
1          1 (flat, cum) 0.0017% of Total
.          .    228:	f.reindex()
.          .    229:
}         .          .    230:
.          .    231:// reindex rebuilds …
```
> Lower number of allocation in freelist.reindex()

- cmd/bolt/main.go
- cmd/bolt/main_test.go
This adds a `compact` to the bolt tool. It recursively inspects a bolt database and copies its keys to a new database.
This usually results in a compacted database, especially if there was a lot of deleted keys with large values. See #308 
Thanks for taking a look at this!
> Compact db

- bolt_386.go
- bolt_amd64.go
- bolt_arm.go
- bolt_arm64.go
- bolt_ppc64le.go
- bolt_s390x.go
- bucket.go
armv5 devices and older (i.e. <= arm9 generation) require addresses that are stored to and loaded from to to be 4-byte aligned.
If this is not the case the lower 2 bits of the address are cleared and the load is performed in an unexpected order, including up to 3 bytes of data located prior to the address.
Inlined buckets are stored after their key in a page and since there is no guarantee that the key will be of a length that is a multiple of 4, it is possible for unaligned load/stores to occur when they are cast back to bucket and page pointer types.
The fix adds a new field to track whether the current architecture exhibits this issue, sets it on module load for ARM architectures, and then on bucket open, if this field is set and the address is unaligned, a byte-by-byte copy of the …
> Correct broken unaligned load/store in armv5

- db.go
The subtraction for `TxN` was previously transposed which caused the result to be a negative number. This change alters the order to return the correct (positive) result.
/cc @evandigby
> Fix Stats.Sub() for Stats.TxN.

- README.md
[bolter](https://github.com/hasit/bolter) is a command-line app for viewing BoltDB file in your terminal using [tablewriter](https://github.com/olekukonko/tablewriter).
> Add 'bolter' to the list of projects that use Bolt

- bolt_ppc64.go
The variable `brokenUnaligned` was missing for ppc64.
> [ppc64] added missing variable

- README.md
Add limitation about multiple processes opening databases concurrently.
Fixes #634.
> Document multi-process limitation in README

- freelist.go
- page.go
- tx.go
Using a large (50gb) database with a read-write-delete heavy load,
nearly 100% of allocated space came from freelists.
1/3 came from freelist.release, 1/3 from freelist.write,
and 1/3 came from tx.allocate to make space for freelist.write.
In the case of freelist.write, the newly allocated giant slice gets
copied to the space prepared by tx.allocate and then discarded.
To avoid this, add func mergepgids that accepts a destination slice,
and use it in freelist.write.
This has a mild negative impact on the existing benchmarks,
but cuts allocated space in my real world db by over 30%.
```
name                      old time/op    new time/op    delta
_FreelistRelease10K-8       18.7µs ±10%    18.2µs ± 4%    ~             (p=0.548 n=5+5)
_FreelistRelease100K-8       233µs ± 5%     258µs ±20% …
```
> Don't allocate huge slices to merge pgids in freelist.write

- bolt_windows.go
- bucket.go
There was a return statement at the end of a function nested inside an else statement. I removed the else block and unindented the code.
I also ran gofmt on the windows file for a minor semantic change.
Signed-off-by: nick <nicholasjamesrusso@gmail.com>
> Fix return statement inside else block at the end of function

- quick_test.go
Quick seed 21691 used to generate duplicate keys, 
which caused some Puts of values to overwrite other values,
causing spurious test failures.
Fixes #629.
> Ensure that keys generated by testing/quick are unique

- db.go
This is safe, as the only place that creates call values always
explicitly sets err. It's a leftover from an earlier iteration of the
code.
> Remove unnecessary if in batch handling
