db.go
The max mmap size was previous unchecked which resulted in a panic once the maximum size was reached. This commit adds a check for the max size when re-mapping and returns an error if the new map will exceed the size.
_Note: Exceeding the max size did **not** cause corruption. It simple caused a panic._
Thanks to Tamás Gulácsi (@tgulacsi) for testing out the change on i386.
=> Add check for max mmap size.

db.go, db_test.go
This pull request fixes an issue where large databases were being resized to larger sizes on every open.
Fixes #303.
=> Fix large mmap resize

README.md
This article would be a good addition the resources
=> link to Bolt article

README.md, bucket.go, cursor.go
This commit adds safety documentation to the data accessor functions in Bolt as well as the README. This was documented once in the package level godoc but it's important enough that it should be more clear.
---
/cc @mschoch
=> Document key/value safety.

README.md
=> Update README.md: fixed type mismatch

README.md
Adding prometheus annotation server to the list projects using BoltDB.
=> Update README.md - add project

tx_test.go
Adds test coverage for these lines: https://github.com/boltdb/bolt/blob/master/tx.go#L112-L122
```
[zsh|matt@nerr-2]:~/git/go/src/github.com/boltdb/bolt 0 (test_tx_foreach) ± go test -v -run=TestTx_ForEach
seed: 87317
quick settings: count=5, items=1000, ksize=1024, vsize=1024
=== RUN TestTx_ForEach_NoError
--- PASS: TestTx_ForEach_NoError (0.01s)
=== RUN TestTx_ForEach_WithError
--- PASS: TestTx_ForEach_WithError (0.02s)
PASS
ok      github.com/boltdb/bolt  0.032s
```
=> tx_test: add tests for two tx.ForEach cases

bucket.go
=> Document undefined behavior in ForEach

README.md
See: https://github.com/boltdb/bolt/issues/436
=> Add example of NextSequence() usage to readme

bolt_ppc64le.go, bolt_s390x.go
Signed-off-by: Srini Brahmaroutu <srbrahma@us.ibm.com>
=> adding seperate files to compile on IBM Power and Z

README.md
This pull request adds a section to help people understand the source better while reading it.
/cc @cpalone
=> README: Add 'Reading the Source' section

simulation_test.go
TestSimulate_1op_1p should be passing 1 as the threadCount instead of 100.
=> Wrong threadCount passed to TestSimulate_1op_1p

bolt_arm64.go
=> Revert "Remove erroneous build constraint from arm64"

README.md
Created a library that allows storage / retrieval of data from nested buckets.
=> Add mbuckets to list of projects using Bolt

bolt_ppc64.go
=> new bolt_ppc64.go similar to bolt_ppc64le.go

tx.go
This commits fixes a timing bug where `DB.StrictMode` can panic before the goroutine reading the database can finish. If an error is found in strict mode then it now finishes reading the entire database before panicking.
_Note: Strict mode should only be used for debugging low level issues so this should not affect production users._
=> Fix strict mode

README.md
Added GoWebApp as a project that uses Bolt.
=> Add GoWebApp as a project that uses Bolt.

README.md
Added two more projects to the README.
=> Add SimpleBolt and Algernon

README.md
I added my project [MuLiFS](https://github.com/dankomiocevic/mulifs) to the list of projects using Bolt.
It is a Music Library Filesystem that helps to organise your music and playlists. It still needs more testing but its core functionality is working.
Hope is useful!
=> Add MuLiFS to the list of projects using Bolt.

README.md
I think that SkyDB is over, I could find any link to the project.
=> Remove skydb of the README

README.md
I have added a BoltDB related project.  https://github.com/evnix/boltdbweb
I built it for my personal use as it becomes really easy to experiment with BoltDB.
I think this will be useful for others as well :)
=> added a BoltDB related project

README.md
The description was too old so i figured i could update it
=> Update description of project using BoltDB

bucket.go, bucket_test.go, cmd/bolt/main.go, cmd/bolt/main_test.go
This pull request combines the `bolt compact` changes from #460 with an additional commit with minor changes to coding style as well as the introduction of `Bucket.Sequence()` and `Bucket.SetSequence()`.
=> Compaction Command

cmd/bolt/main.go
=> task#560 print leaf k/v with right value

README.md
Hi,
Could you add GopherPit to the list of projects that use Bolt as the storage library?
Thank you,
Janoš
=> Add gopherpit to projects that use Bolt

README.md
After our conversation here is a better example for nested buckets.
=> enhc: update example for nested buckets

db.go, freelist.go, page.go, tx.go
These all came from reading the code, although I believe the two bug fixes solve potentially real issues.
=> Minor cleanup and bug fixes

bolt_unix.go
fixes #600. For some reason this test fails for me locally. Ignore the previous comment that was because I was putting a timeout on my tests that was too low. All tests pass and glusterfs now works as expected when locking files.
=> replace unix implementation to be the same as solaris to fix an issue with glusterfs

cmd/bolt/main.go
=> hexidecimal -> hexadecimal

bolt_unix.go
Reverts a previous commit based on feedback from https://github.com/boltdb/bolt/issues/653#issuecomment-276383239.
/cc @schollz
=> Revert "replace unix implementation to be the same as solaris to fix …"
